---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Find EXTERNALLY-MANAGED files
      ansible.builtin.find:
        paths: /usr/lib
        patterns: "EXTERNALLY-MANAGED"
        recurse: true
      register: externally_managed_files

    - name: Remove EXTERNALLY-MANAGED files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ externally_managed_files.files }}"

  roles:
    - role: buluma.bootstrap

  tasks:
    - name: Install apt-transport-https ca-certificates
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - apt-transport-https
        - ca-certificates

    - name: Install yarn public key
      ansible.builtin.apt_key:
        url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
        validate_certs: false
